spring:
    datasource:
      url: jdbc:mysql://101.200.47.113:3306/ishare?characterEncoding=UTF-8
      #url: jdbc:mysql://10.115.0.29:3306/ishare?characterEncoding=UTF-8
      username: df
      password: 123456
      #schema: database/import.sql
      sql-script-encoding: UTF-8
      driver-class-name: com.mysql.jdbc.Driver
    http: 
      multipart:
        max-file-size: 10240KB
        max-request-size: 10240KB

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
         current_session_context_class: thread

    thymeleaf:
       cache: false
       mode: LEGACYHTML5 
       encoding: UTF-8
